### ISSUE TITLE
v0.1.6 Error: No native build was found for platform=linux arch=arm runtime=node abi=57 uv=1 armv=6 libc=glibc

### ISSUE THREAD

**Issue by allanhvam** [tim-hellhake/enocean-adapter#9]
After the automatic update yesterday, by enocean adapter fails to start.

Logs:
2020-02-05 20:05:49.267 INFO   : enocean: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-02-05 20:05:50.610 INFO   : enocean: Loading add-on enocean-adapter from /home/pi/.mozilla-iot/addons/enocean-adapter
2020-02-05 20:05:50.876 ERROR  : enocean: Error: No native build was found for platform=linux arch=arm runtime=node abi=57 uv=1 armv=6 libc=glibc
2020-02-05 20:05:50.878 ERROR  : enocean:     at Function.load.path (/home/pi/.mozilla-iot/addons/enocean-adapter/node_modules/node-gyp-build/index.js:56:9)
2020-02-05 20:05:50.880 ERROR  : enocean:     at load (/home/pi/.mozilla-iot/addons/enocean-adapter/node_modules/node-gyp-build/index.js:20:30)
2020-02-05 20:05:50.881 ERROR  : enocean:     at Object.<anonymous> (/home/pi/.mozilla-iot/addons/enocean-adapter/node_modules/leveldown/binding.js:1:105)
2020-02-05 20:05:50.883 ERROR  : enocean:     at Module._compile (module.js:653:30)
2020-02-05 20:05:50.884 ERROR  : enocean:     at Object.Module._extensions..js (module.js:664:10)
2020-02-05 20:05:50.885 ERROR  : enocean:     at Module.load (module.js:566:32)
2020-02-05 20:05:50.887 ERROR  : enocean:     at tryModuleLoad (module.js:506:12)
2020-02-05 20:05:50.888 ERROR  : enocean:     at Function.Module._load (module.js:498:3)
2020-02-05 20:05:50.889 ERROR  : enocean:     at Module.require (module.js:597:17)
2020-02-05 20:05:50.890 ERROR  : enocean:     at require (internal/module.js:11:18)

Running on Raspberry Pi model B+, webthings 0.10.0 and node v8.16.2

Do I need to upgrade to node 10? 12? and how? Or are there other solutions on how to solve this?

**Comment by tim-hellhake** [comment]
> Do I need to upgrade to node 10? 12? and how? Or are there other solutions on how to solve this?

No this is a bug.
The adapter is cross-compiled for different platforms.
Looks like something went wrong.
I'll check it.

**Comment by tim-hellhake** [comment]
@allanhvam
There was a problem with the cross-compilation.
Version 0.1.7 should run without problems.
